import { Inter, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "../Components/Navbar.tsx";
import Footer from "../Components/Footer.tsx";
import WorkoutProvider from "../context/WorkoutContext.tsx";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});


export const metadata = {
  title: "Assignment-6",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${inter.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-full flex flex-col bg-black ">
        <WorkoutProvider>

          <Navbar></Navbar>
          <main >
            {children}
            <ToastContainer />
          </main>
          <Footer></Footer>
        </WorkoutProvider>
      </body>
    </html>
  );
}
